sudo: required

services:
  - docker

env:
  global:
    - appUser="media"
    - appGroup="1000"

install:
  - docker build . -t ../sabnzbd

script:
  - rundocker.sh
  - bats tests/

notifications:
  email: false
