sudo: required

services:
  - docker

env:
  global:
    - appUser="media"
    - appGroup="1000"

install:
  - scorputty/sabnzbd/build.sh

script:
  - scorputty/sabnzbd/rundocker.sh
  - bats scorputty/sabnzbd/tests/

notifications:
  email: false
