sudo: required

services:
  - docker

env:
  - OS_TYPE=centos OS_VERSION=7 ANSIBLE_VERSION=2.2.0.0

install:
  - docker build --rm --no-cache -t cryptout/sabnzbd ../sabnzbd

script:
  - ./rundocker.sh
  - sleep 10
  - bats tests/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cryptout/sabnzbd:latest;
    fi

notifications:
  email: false
