sudo: required

services:
  - docker

env:
  global:
    - appUser="media"
    - appGroup="1000"

install:
  - ./sabnzbd/build.sh

script:
  - ./sabnzbd/rundocker.sh
  - bats sabnzbd/tests/

notifications:
  email: false
